apiVersion: 1

datasources:
    - name: VictoriaMetrics
      type: prometheus
      access: proxy
      url: http://vmauth.cloud-infrastructure-storage.localstack.domain:8427
      isDefault: true
      basicAuth: true
      basicAuthUser: grafana_username
      secureJsonData:
        basicAuthPassword: grafana_password
