{
 "title": "service-simple-backend",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "sio_pings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_del(backend_service_sio_pings, \"creator\") or on() vector(0)"
    }
   ]
  },
  {
   "title": "detection readings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "label_keep(backend_service_detections_type{type=\"reading\"}, \"code\")"
    }
   ]
  },
  {
   "title": "detections_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "label_del(backend_service_detections_count, \"creator\")"
    }
   ]
  },
  {
   "title": "detections_sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(label_del(backend_service_detections_sent, \"creator\"))",
     "legendFormat": "detections_sent"
    }
   ]
  },
  {
   "title": "detections time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "label_del(backend_service_detect_microsecond_time, \"creator\")"
    }
   ]
  }
 ]
}