{
 "title": "service-simple-frontend",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Ping vs pong",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_del(frontend_service_sio_ping, \"creator\") or on() vector(0)"
    },
    {
     "expr": "label_del(frontend_service_sio_pong, \"creator\") or on() vector(0)"
    }
   ]
  },
  {
   "title": "detections type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_keep(frontend_service_detections_type_detections, \"type\")"
    }
   ]
  },
  {
   "title": "detections_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "label_del(frontend_service_detections_count_detections, \"creator\")"
    }
   ]
  },
  {
   "title": "detections_received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "label_del(frontend_service_detections_received, \"creator\") or on() vector(0)"
    }
   ]
  }
 ]
}