{
 "title": "system-telegraf-ping",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(telegraf_ping_average_response_ms, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "telegraf_ping_average_response_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_del(telegraf_ping_average_response_ms{host=~\"$host\"}, \"db\")"
    }
   ]
  },
  {
   "title": "telegraf_ping_maximum_response_ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "label_del(telegraf_ping_maximum_response_ms{host=~\"$host\"}, \"db\")"
    }
   ]
  },
  {
   "title": "telegraf_ping_minimum_response_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "label_del(telegraf_ping_minimum_response_ms{host=~\"$host\"}, \"db\")"
    }
   ]
  },
  {
   "title": "telegraf_ping_packets_received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "label_del(telegraf_ping_packets_received{host=~\"$host\"}, \"db\")"
    }
   ]
  },
  {
   "title": "telegraf_ping_packets_transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "label_del(telegraf_ping_packets_transmitted{host=~\"$host\"}, \"db\")"
    }
   ]
  },
  {
   "title": "telegraf_ping_percent_packet_loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "label_del(telegraf_ping_percent_packet_loss{host=~\"$host\"}, \"db\")"
    }
   ]
  },
  {
   "title": "telegraf_ping_result_code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "label_del(telegraf_ping_result_code{host=~\"$host\"}, \"db\")"
    }
   ]
  },
  {
   "title": "telegraf_ping_standard_deviation_ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "telegraf_ping_standard_deviation_ms"
    }
   ]
  },
  {
   "title": "telegraf_ping_ttl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "label_del(telegraf_ping_ttl{host=~\"$host\"}, \"db\")"
    }
   ]
  }
 ]
}