{
 "title": "system-telegraf-hosts",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(telegraf_system_uptime, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "OS Version count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (dist_desc) (lsb_dist_counter_host_counter) or on() vector(0)"
    }
   ]
  },
  {
   "title": "kernels",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (kernel) (lsb_dist_counter_host_counter) or on() vector(0)"
    }
   ]
  },
  {
   "title": "temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "telegraf_temp_temp{host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "system_uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(telegraf_system_uptime{host=~\"$host\"}) or on() vector(0)"
    }
   ]
  },
  {
   "title": "mem_available_percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "label_keep(telegraf_mem_available_percent{host=~\"$host\"}, \"host\") "
    }
   ]
  },
  {
   "title": "cpu_usage_system",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "label_keep(telegraf_cpu_usage_system{cpu=\"cpu-total\", host=~\"$host\"}, \"cpu\", \"host\")"
    }
   ]
  },
  {
   "title": "diskio_iops_in_progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "label_keep(telegraf_diskio_iops_in_progress{host=~\"$host\"}, \"host\", \"name\") or on() vector(0)"
    }
   ]
  }
 ]
}