up:
	(cd ubuntu-18-04-bionic && make up)
	(cd ubuntu-20-04-focal && make up)
	(cd ubuntu-22-04-jammy && make up)

re-provision:
	(cd ubuntu-18-04-bionic && make re-provision)
	(cd ubuntu-20-04-focal && make re-provision)
	(cd ubuntu-22-04-jammy && make re-provision)

down:
	(cd ubuntu-18-04-bionic && make down)
	(cd ubuntu-20-04-focal && make down)
	(cd ubuntu-22-04-jammy && make down)

stop:
	make down

ps:
	(cd ubuntu-18-04-bionic && make ps)
	(cd ubuntu-20-04-focal && make ps)
	(cd ubuntu-22-04-jammy && make ps)
